package me.mcblueparrot.spade.api.block;

import java.util.List;
import java.util.Objects;

import me.mcblueparrot.spade.api.Spade;
import me.mcblueparrot.spade.api.Taggable;
import me.mcblueparrot.spade.api.id.Identifiable;
import me.mcblueparrot.spade.api.id.Identifier;
import me.mcblueparrot.spade.api.server.Server;

/**
 * Represents a type of block.
 */
public abstract class BlockType implements Identifiable, Taggable {

	private Identifier id;

	protected BlockType(Identifier id) {
		this.id = id;
	}

	/**
	 * Gets the block type's identifier.
	 * @return the identifier
	 */
	@Override
	public Identifier getId() {
		return id;
	}

	/**
	 * Gets the block type's blast resistance.
	 * @return the block type's blast resistance
	 */
	public abstract float getBlastResistance();

	/**
	 * Gets the block type's slipperiness.
	 * @return the block type's slipperiness
	 */
	public abstract float getSlipperiness();

	@Override
	public String toString() {
		return id.toString();
	}

	@Override
	public int hashCode() {
		return Objects.hash(id);
	}

	@Override
	public boolean equals(Object obj) {
		if(this == obj) {
			return true;
		}
		if(obj == null) {
			return false;
		}
		if(getClass() != obj.getClass()) {
			return false;
		}
		BlockType other = (BlockType) obj;
		return Objects.equals(id, other.id);
	}

	/**
	 * @see Server#getBlockType(Identifier)
	 */
	public static BlockType getBlockType(Identifier id) {
		return Spade.getBlockType(id);
	}

	/**
	 * @see Server#getBlockType(String)
	 */
	public static BlockType getBlockType(String id) {
		return Spade.getBlockType(id);
	}

	/**
	 * @see Server#getBlockTypes()
	 */
	public static List<BlockType> getBlockTypes() {
		return Spade.getBlockTypes();
	}

	public static final BlockType AIR = getBlockType("air");
	public static final BlockType STONE = getBlockType("stone");
	public static final BlockType GRANITE = getBlockType("granite");
	public static final BlockType POLISHED_GRANITE = getBlockType("polished_granite");
	public static final BlockType DIORITE = getBlockType("diorite");
	public static final BlockType POLISHED_DIORITE = getBlockType("polished_diorite");
	public static final BlockType ANDESITE = getBlockType("andesite");
	public static final BlockType POLISHED_ANDESITE = getBlockType("polished_andesite");
	public static final BlockType GRASS_BLOCK = getBlockType("grass_block");
	public static final BlockType DIRT = getBlockType("dirt");
	public static final BlockType COARSE_DIRT = getBlockType("coarse_dirt");
	public static final BlockType PODZOL = getBlockType("podzol");
	public static final BlockType COBBLESTONE = getBlockType("cobblestone");
	public static final BlockType OAK_PLANKS = getBlockType("oak_planks");
	public static final BlockType SPRUCE_PLANKS = getBlockType("spruce_planks");
	public static final BlockType BIRCH_PLANKS = getBlockType("birch_planks");
	public static final BlockType JUNGLE_PLANKS = getBlockType("jungle_planks");
	public static final BlockType ACACIA_PLANKS = getBlockType("acacia_planks");
	public static final BlockType DARK_OAK_PLANKS = getBlockType("dark_oak_planks");
	public static final BlockType OAK_SAPLING = getBlockType("oak_sapling");
	public static final BlockType SPRUCE_SAPLING = getBlockType("spruce_sapling");
	public static final BlockType BIRCH_SAPLING = getBlockType("birch_sapling");
	public static final BlockType JUNGLE_SAPLING = getBlockType("jungle_sapling");
	public static final BlockType ACACIA_SAPLING = getBlockType("acacia_sapling");
	public static final BlockType DARK_OAK_SAPLING = getBlockType("dark_oak_sapling");
	public static final BlockType BEDROCK = getBlockType("bedrock");
	public static final BlockType WATER = getBlockType("water");
	public static final BlockType LAVA = getBlockType("lava");
	public static final BlockType SAND = getBlockType("sand");
	public static final BlockType RED_SAND = getBlockType("red_sand");
	public static final BlockType GRAVEL = getBlockType("gravel");
	public static final BlockType GOLD_ORE = getBlockType("gold_ore");
	public static final BlockType IRON_ORE = getBlockType("iron_ore");
	public static final BlockType COAL_ORE = getBlockType("coal_ore");
	public static final BlockType NETHER_GOLD_ORE = getBlockType("nether_gold_ore");
	public static final BlockType OAK_LOG = getBlockType("oak_log");
	public static final BlockType SPRUCE_LOG = getBlockType("spruce_log");
	public static final BlockType BIRCH_LOG = getBlockType("birch_log");
	public static final BlockType JUNGLE_LOG = getBlockType("jungle_log");
	public static final BlockType ACACIA_LOG = getBlockType("acacia_log");
	public static final BlockType DARK_OAK_LOG = getBlockType("dark_oak_log");
	public static final BlockType STRIPPED_SPRUCE_LOG = getBlockType("stripped_spruce_log");
	public static final BlockType STRIPPED_BIRCH_LOG = getBlockType("stripped_birch_log");
	public static final BlockType STRIPPED_JUNGLE_LOG = getBlockType("stripped_jungle_log");
	public static final BlockType STRIPPED_ACACIA_LOG = getBlockType("stripped_acacia_log");
	public static final BlockType STRIPPED_DARK_OAK_LOG = getBlockType("stripped_dark_oak_log");
	public static final BlockType STRIPPED_OAK_LOG = getBlockType("stripped_oak_log");
	public static final BlockType OAK_WOOD = getBlockType("oak_wood");
	public static final BlockType SPRUCE_WOOD = getBlockType("spruce_wood");
	public static final BlockType BIRCH_WOOD = getBlockType("birch_wood");
	public static final BlockType JUNGLE_WOOD = getBlockType("jungle_wood");
	public static final BlockType ACACIA_WOOD = getBlockType("acacia_wood");
	public static final BlockType DARK_OAK_WOOD = getBlockType("dark_oak_wood");
	public static final BlockType STRIPPED_OAK_WOOD = getBlockType("stripped_oak_wood");
	public static final BlockType STRIPPED_SPRUCE_WOOD = getBlockType("stripped_spruce_wood");
	public static final BlockType STRIPPED_BIRCH_WOOD = getBlockType("stripped_birch_wood");
	public static final BlockType STRIPPED_JUNGLE_WOOD = getBlockType("stripped_jungle_wood");
	public static final BlockType STRIPPED_ACACIA_WOOD = getBlockType("stripped_acacia_wood");
	public static final BlockType STRIPPED_DARK_OAK_WOOD = getBlockType("stripped_dark_oak_wood");
	public static final BlockType OAK_LEAVES = getBlockType("oak_leaves");
	public static final BlockType SPRUCE_LEAVES = getBlockType("spruce_leaves");
	public static final BlockType BIRCH_LEAVES = getBlockType("birch_leaves");
	public static final BlockType JUNGLE_LEAVES = getBlockType("jungle_leaves");
	public static final BlockType ACACIA_LEAVES = getBlockType("acacia_leaves");
	public static final BlockType DARK_OAK_LEAVES = getBlockType("dark_oak_leaves");
	public static final BlockType SPONGE = getBlockType("sponge");
	public static final BlockType WET_SPONGE = getBlockType("wet_sponge");
	public static final BlockType GLASS = getBlockType("glass");
	public static final BlockType LAPIS_ORE = getBlockType("lapis_ore");
	public static final BlockType LAPIS_BLOCK = getBlockType("lapis_block");
	public static final BlockType DISPENSER = getBlockType("dispenser");
	public static final BlockType SANDSTONE = getBlockType("sandstone");
	public static final BlockType CHISELED_SANDSTONE = getBlockType("chiseled_sandstone");
	public static final BlockType CUT_SANDSTONE = getBlockType("cut_sandstone");
	public static final BlockType NOTE_BLOCK = getBlockType("note_block");
	public static final BlockType WHITE_BED = getBlockType("white_bed");
	public static final BlockType ORANGE_BED = getBlockType("orange_bed");
	public static final BlockType MAGENTA_BED = getBlockType("magenta_bed");
	public static final BlockType LIGHT_BLUE_BED = getBlockType("light_blue_bed");
	public static final BlockType YELLOW_BED = getBlockType("yellow_bed");
	public static final BlockType LIME_BED = getBlockType("lime_bed");
	public static final BlockType PINK_BED = getBlockType("pink_bed");
	public static final BlockType GRAY_BED = getBlockType("gray_bed");
	public static final BlockType LIGHT_GRAY_BED = getBlockType("light_gray_bed");
	public static final BlockType CYAN_BED = getBlockType("cyan_bed");
	public static final BlockType PURPLE_BED = getBlockType("purple_bed");
	public static final BlockType BLUE_BED = getBlockType("blue_bed");
	public static final BlockType BROWN_BED = getBlockType("brown_bed");
	public static final BlockType GREEN_BED = getBlockType("green_bed");
	public static final BlockType RED_BED = getBlockType("red_bed");
	public static final BlockType BLACK_BED = getBlockType("black_bed");
	public static final BlockType POWERED_RAIL = getBlockType("powered_rail");
	public static final BlockType DETECTOR_RAIL = getBlockType("detector_rail");
	public static final BlockType STICKY_PISTON = getBlockType("sticky_piston");
	public static final BlockType COBWEB = getBlockType("cobweb");
	public static final BlockType GRASS = getBlockType("grass");
	public static final BlockType FERN = getBlockType("fern");
	public static final BlockType DEAD_BUSH = getBlockType("dead_bush");
	public static final BlockType SEAGRASS = getBlockType("seagrass");
	public static final BlockType TALL_SEAGRASS = getBlockType("tall_seagrass");
	public static final BlockType PISTON = getBlockType("piston");
	public static final BlockType PISTON_HEAD = getBlockType("piston_head");
	public static final BlockType WHITE_WOOL = getBlockType("white_wool");
	public static final BlockType ORANGE_WOOL = getBlockType("orange_wool");
	public static final BlockType MAGENTA_WOOL = getBlockType("magenta_wool");
	public static final BlockType LIGHT_BLUE_WOOL = getBlockType("light_blue_wool");
	public static final BlockType YELLOW_WOOL = getBlockType("yellow_wool");
	public static final BlockType LIME_WOOL = getBlockType("lime_wool");
	public static final BlockType PINK_WOOL = getBlockType("pink_wool");
	public static final BlockType GRAY_WOOL = getBlockType("gray_wool");
	public static final BlockType LIGHT_GRAY_WOOL = getBlockType("light_gray_wool");
	public static final BlockType CYAN_WOOL = getBlockType("cyan_wool");
	public static final BlockType PURPLE_WOOL = getBlockType("purple_wool");
	public static final BlockType BLUE_WOOL = getBlockType("blue_wool");
	public static final BlockType BROWN_WOOL = getBlockType("brown_wool");
	public static final BlockType GREEN_WOOL = getBlockType("green_wool");
	public static final BlockType RED_WOOL = getBlockType("red_wool");
	public static final BlockType BLACK_WOOL = getBlockType("black_wool");
	public static final BlockType MOVING_PISTON = getBlockType("moving_piston");
	public static final BlockType DANDELION = getBlockType("dandelion");
	public static final BlockType POPPY = getBlockType("poppy");
	public static final BlockType BLUE_ORCHID = getBlockType("blue_orchid");
	public static final BlockType ALLIUM = getBlockType("allium");
	public static final BlockType AZURE_BLUET = getBlockType("azure_bluet");
	public static final BlockType RED_TULIP = getBlockType("red_tulip");
	public static final BlockType ORANGE_TULIP = getBlockType("orange_tulip");
	public static final BlockType WHITE_TULIP = getBlockType("white_tulip");
	public static final BlockType PINK_TULIP = getBlockType("pink_tulip");
	public static final BlockType OXEYE_DAISY = getBlockType("oxeye_daisy");
	public static final BlockType CORNFLOWER = getBlockType("cornflower");
	public static final BlockType WITHER_ROSE = getBlockType("wither_rose");
	public static final BlockType LILY_OF_THE_VALLEY = getBlockType("lily_of_the_valley");
	public static final BlockType BROWN_MUSHROOM = getBlockType("brown_mushroom");
	public static final BlockType RED_MUSHROOM = getBlockType("red_mushroom");
	public static final BlockType GOLD_BLOCK = getBlockType("gold_block");
	public static final BlockType IRON_BLOCK = getBlockType("iron_block");
	public static final BlockType BRICKS = getBlockType("bricks");
	public static final BlockType TNT = getBlockType("tnt");
	public static final BlockType BOOKSHELF = getBlockType("bookshelf");
	public static final BlockType MOSSY_COBBLESTONE = getBlockType("mossy_cobblestone");
	public static final BlockType OBSIDIAN = getBlockType("obsidian");
	public static final BlockType TORCH = getBlockType("torch");
	public static final BlockType WALL_TORCH = getBlockType("wall_torch");
	public static final BlockType FIRE = getBlockType("fire");
	public static final BlockType SOUL_FIRE = getBlockType("soul_fire");
	public static final BlockType SPAWNER = getBlockType("spawner");
	public static final BlockType OAK_STAIRS = getBlockType("oak_stairs");
	public static final BlockType CHEST = getBlockType("chest");
	public static final BlockType REDSTONE_WIRE = getBlockType("redstone_wire");
	public static final BlockType DIAMOND_ORE = getBlockType("diamond_ore");
	public static final BlockType DIAMOND_BLOCK = getBlockType("diamond_block");
	public static final BlockType CRAFTING_TABLE = getBlockType("crafting_table");
	public static final BlockType WHEAT = getBlockType("wheat");
	public static final BlockType FARMLAND = getBlockType("farmland");
	public static final BlockType FURNACE = getBlockType("furnace");
	public static final BlockType OAK_SIGN = getBlockType("oak_sign");
	public static final BlockType SPRUCE_SIGN = getBlockType("spruce_sign");
	public static final BlockType BIRCH_SIGN = getBlockType("birch_sign");
	public static final BlockType ACACIA_SIGN = getBlockType("acacia_sign");
	public static final BlockType JUNGLE_SIGN = getBlockType("jungle_sign");
	public static final BlockType DARK_OAK_SIGN = getBlockType("dark_oak_sign");
	public static final BlockType OAK_DOOR = getBlockType("oak_door");
	public static final BlockType LADDER = getBlockType("ladder");
	public static final BlockType RAIL = getBlockType("rail");
	public static final BlockType COBBLESTONE_STAIRS = getBlockType("cobblestone_stairs");
	public static final BlockType OAK_WALL_SIGN = getBlockType("oak_wall_sign");
	public static final BlockType SPRUCE_WALL_SIGN = getBlockType("spruce_wall_sign");
	public static final BlockType BIRCH_WALL_SIGN = getBlockType("birch_wall_sign");
	public static final BlockType ACACIA_WALL_SIGN = getBlockType("acacia_wall_sign");
	public static final BlockType JUNGLE_WALL_SIGN = getBlockType("jungle_wall_sign");
	public static final BlockType DARK_OAK_WALL_SIGN = getBlockType("dark_oak_wall_sign");
	public static final BlockType LEVER = getBlockType("lever");
	public static final BlockType STONE_PRESSURE_PLATE = getBlockType("stone_pressure_plate");
	public static final BlockType IRON_DOOR = getBlockType("iron_door");
	public static final BlockType OAK_PRESSURE_PLATE = getBlockType("oak_pressure_plate");
	public static final BlockType SPRUCE_PRESSURE_PLATE = getBlockType("spruce_pressure_plate");
	public static final BlockType BIRCH_PRESSURE_PLATE = getBlockType("birch_pressure_plate");
	public static final BlockType JUNGLE_PRESSURE_PLATE = getBlockType("jungle_pressure_plate");
	public static final BlockType ACACIA_PRESSURE_PLATE = getBlockType("acacia_pressure_plate");
	public static final BlockType DARK_OAK_PRESSURE_PLATE = getBlockType("dark_oak_pressure_plate");
	public static final BlockType REDSTONE_ORE = getBlockType("redstone_ore");
	public static final BlockType REDSTONE_TORCH = getBlockType("redstone_torch");
	public static final BlockType REDSTONE_WALL_TORCH = getBlockType("redstone_wall_torch");
	public static final BlockType STONE_BUTTON = getBlockType("stone_button");
	public static final BlockType SNOW = getBlockType("snow");
	public static final BlockType ICE = getBlockType("ice");
	public static final BlockType SNOW_BLOCK = getBlockType("snow_block");
	public static final BlockType CACTUS = getBlockType("cactus");
	public static final BlockType CLAY = getBlockType("clay");
	public static final BlockType SUGAR_CANE = getBlockType("sugar_cane");
	public static final BlockType JUKEBOX = getBlockType("jukebox");
	public static final BlockType OAK_FENCE = getBlockType("oak_fence");
	public static final BlockType PUMPKIN = getBlockType("pumpkin");
	public static final BlockType NETHERRACK = getBlockType("netherrack");
	public static final BlockType SOUL_SAND = getBlockType("soul_sand");
	public static final BlockType SOUL_SOIL = getBlockType("soul_soil");
	public static final BlockType BASALT = getBlockType("basalt");
	public static final BlockType POLISHED_BASALT = getBlockType("polished_basalt");
	public static final BlockType SOUL_TORCH = getBlockType("soul_torch");
	public static final BlockType SOUL_WALL_TORCH = getBlockType("soul_wall_torch");
	public static final BlockType GLOWSTONE = getBlockType("glowstone");
	public static final BlockType NETHER_PORTAL = getBlockType("nether_portal");
	public static final BlockType CARVED_PUMPKIN = getBlockType("carved_pumpkin");
	public static final BlockType JACK_O_LANTERN = getBlockType("jack_o_lantern");
	public static final BlockType CAKE = getBlockType("cake");
	public static final BlockType REPEATER = getBlockType("repeater");
	public static final BlockType WHITE_STAINED_GLASS = getBlockType("white_stained_glass");
	public static final BlockType ORANGE_STAINED_GLASS = getBlockType("orange_stained_glass");
	public static final BlockType MAGENTA_STAINED_GLASS = getBlockType("magenta_stained_glass");
	public static final BlockType LIGHT_BLUE_STAINED_GLASS = getBlockType("light_blue_stained_glass");
	public static final BlockType YELLOW_STAINED_GLASS = getBlockType("yellow_stained_glass");
	public static final BlockType LIME_STAINED_GLASS = getBlockType("lime_stained_glass");
	public static final BlockType PINK_STAINED_GLASS = getBlockType("pink_stained_glass");
	public static final BlockType GRAY_STAINED_GLASS = getBlockType("gray_stained_glass");
	public static final BlockType LIGHT_GRAY_STAINED_GLASS = getBlockType("light_gray_stained_glass");
	public static final BlockType CYAN_STAINED_GLASS = getBlockType("cyan_stained_glass");
	public static final BlockType PURPLE_STAINED_GLASS = getBlockType("purple_stained_glass");
	public static final BlockType BLUE_STAINED_GLASS = getBlockType("blue_stained_glass");
	public static final BlockType BROWN_STAINED_GLASS = getBlockType("brown_stained_glass");
	public static final BlockType GREEN_STAINED_GLASS = getBlockType("green_stained_glass");
	public static final BlockType RED_STAINED_GLASS = getBlockType("red_stained_glass");
	public static final BlockType BLACK_STAINED_GLASS = getBlockType("black_stained_glass");
	public static final BlockType OAK_TRAPDOOR = getBlockType("oak_trapdoor");
	public static final BlockType SPRUCE_TRAPDOOR = getBlockType("spruce_trapdoor");
	public static final BlockType BIRCH_TRAPDOOR = getBlockType("birch_trapdoor");
	public static final BlockType JUNGLE_TRAPDOOR = getBlockType("jungle_trapdoor");
	public static final BlockType ACACIA_TRAPDOOR = getBlockType("acacia_trapdoor");
	public static final BlockType DARK_OAK_TRAPDOOR = getBlockType("dark_oak_trapdoor");
	public static final BlockType STONE_BRICKS = getBlockType("stone_bricks");
	public static final BlockType MOSSY_STONE_BRICKS = getBlockType("mossy_stone_bricks");
	public static final BlockType CRACKED_STONE_BRICKS = getBlockType("cracked_stone_bricks");
	public static final BlockType CHISELED_STONE_BRICKS = getBlockType("chiseled_stone_bricks");
	public static final BlockType INFESTED_STONE = getBlockType("infested_stone");
	public static final BlockType INFESTED_COBBLESTONE = getBlockType("infested_cobblestone");
	public static final BlockType INFESTED_STONE_BRICKS = getBlockType("infested_stone_bricks");
	public static final BlockType INFESTED_MOSSY_STONE_BRICKS = getBlockType("infested_mossy_stone_bricks");
	public static final BlockType INFESTED_CRACKED_STONE_BRICKS = getBlockType("infested_cracked_stone_bricks");
	public static final BlockType INFESTED_CHISELED_STONE_BRICKS = getBlockType("infested_chiseled_stone_bricks");
	public static final BlockType BROWN_MUSHROOM_BLOCK = getBlockType("brown_mushroom_block");
	public static final BlockType RED_MUSHROOM_BLOCK = getBlockType("red_mushroom_block");
	public static final BlockType MUSHROOM_STEM = getBlockType("mushroom_stem");
	public static final BlockType IRON_BARS = getBlockType("iron_bars");
	public static final BlockType CHAIN = getBlockType("chain");
	public static final BlockType GLASS_PANE = getBlockType("glass_pane");
	public static final BlockType MELON = getBlockType("melon");
	public static final BlockType ATTACHED_PUMPKIN_STEM = getBlockType("attached_pumpkin_stem");
	public static final BlockType ATTACHED_MELON_STEM = getBlockType("attached_melon_stem");
	public static final BlockType PUMPKIN_STEM = getBlockType("pumpkin_stem");
	public static final BlockType MELON_STEM = getBlockType("melon_stem");
	public static final BlockType VINE = getBlockType("vine");
	public static final BlockType OAK_FENCE_GATE = getBlockType("oak_fence_gate");
	public static final BlockType BRICK_STAIRS = getBlockType("brick_stairs");
	public static final BlockType STONE_BRICK_STAIRS = getBlockType("stone_brick_stairs");
	public static final BlockType MYCELIUM = getBlockType("mycelium");
	public static final BlockType LILY_PAD = getBlockType("lily_pad");
	public static final BlockType NETHER_BRICKS = getBlockType("nether_bricks");
	public static final BlockType NETHER_BRICK_FENCE = getBlockType("nether_brick_fence");
	public static final BlockType NETHER_BRICK_STAIRS = getBlockType("nether_brick_stairs");
	public static final BlockType NETHER_WART = getBlockType("nether_wart");
	public static final BlockType ENCHANTING_TABLE = getBlockType("enchanting_table");
	public static final BlockType BREWING_STAND = getBlockType("brewing_stand");
	public static final BlockType CAULDRON = getBlockType("cauldron");
	public static final BlockType END_PORTAL = getBlockType("end_portal");
	public static final BlockType END_PORTAL_FRAME = getBlockType("end_portal_frame");
	public static final BlockType END_STONE = getBlockType("end_stone");
	public static final BlockType DRAGON_EGG = getBlockType("dragon_egg");
	public static final BlockType REDSTONE_LAMP = getBlockType("redstone_lamp");
	public static final BlockType COCOA = getBlockType("cocoa");
	public static final BlockType SANDSTONE_STAIRS = getBlockType("sandstone_stairs");
	public static final BlockType EMERALD_ORE = getBlockType("emerald_ore");
	public static final BlockType ENDER_CHEST = getBlockType("ender_chest");
	public static final BlockType TRIPWIRE_HOOK = getBlockType("tripwire_hook");
	public static final BlockType TRIPWIRE = getBlockType("tripwire");
	public static final BlockType EMERALD_BLOCK = getBlockType("emerald_block");
	public static final BlockType SPRUCE_STAIRS = getBlockType("spruce_stairs");
	public static final BlockType BIRCH_STAIRS = getBlockType("birch_stairs");
	public static final BlockType JUNGLE_STAIRS = getBlockType("jungle_stairs");
	public static final BlockType COMMAND_BLOCK = getBlockType("command_block");
	public static final BlockType BEACON = getBlockType("beacon");
	public static final BlockType COBBLESTONE_WALL = getBlockType("cobblestone_wall");
	public static final BlockType MOSSY_COBBLESTONE_WALL = getBlockType("mossy_cobblestone_wall");
	public static final BlockType FLOWER_POT = getBlockType("flower_pot");
	public static final BlockType POTTED_OAK_SAPLING = getBlockType("potted_oak_sapling");
	public static final BlockType POTTED_SPRUCE_SAPLING = getBlockType("potted_spruce_sapling");
	public static final BlockType POTTED_BIRCH_SAPLING = getBlockType("potted_birch_sapling");
	public static final BlockType POTTED_JUNGLE_SAPLING = getBlockType("potted_jungle_sapling");
	public static final BlockType POTTED_ACACIA_SAPLING = getBlockType("potted_acacia_sapling");
	public static final BlockType POTTED_DARK_OAK_SAPLING = getBlockType("potted_dark_oak_sapling");
	public static final BlockType POTTED_FERN = getBlockType("potted_fern");
	public static final BlockType POTTED_DANDELION = getBlockType("potted_dandelion");
	public static final BlockType POTTED_POPPY = getBlockType("potted_poppy");
	public static final BlockType POTTED_BLUE_ORCHID = getBlockType("potted_blue_orchid");
	public static final BlockType POTTED_ALLIUM = getBlockType("potted_allium");
	public static final BlockType POTTED_AZURE_BLUET = getBlockType("potted_azure_bluet");
	public static final BlockType POTTED_RED_TULIP = getBlockType("potted_red_tulip");
	public static final BlockType POTTED_ORANGE_TULIP = getBlockType("potted_orange_tulip");
	public static final BlockType POTTED_WHITE_TULIP = getBlockType("potted_white_tulip");
	public static final BlockType POTTED_PINK_TULIP = getBlockType("potted_pink_tulip");
	public static final BlockType POTTED_OXEYE_DAISY = getBlockType("potted_oxeye_daisy");
	public static final BlockType POTTED_CORNFLOWER = getBlockType("potted_cornflower");
	public static final BlockType POTTED_LILY_OF_THE_VALLEY = getBlockType("potted_lily_of_the_valley");
	public static final BlockType POTTED_WITHER_ROSE = getBlockType("potted_wither_rose");
	public static final BlockType POTTED_RED_MUSHROOM = getBlockType("potted_red_mushroom");
	public static final BlockType POTTED_BROWN_MUSHROOM = getBlockType("potted_brown_mushroom");
	public static final BlockType POTTED_DEAD_BUSH = getBlockType("potted_dead_bush");
	public static final BlockType POTTED_CACTUS = getBlockType("potted_cactus");
	public static final BlockType CARROTS = getBlockType("carrots");
	public static final BlockType POTATOES = getBlockType("potatoes");
	public static final BlockType OAK_BUTTON = getBlockType("oak_button");
	public static final BlockType SPRUCE_BUTTON = getBlockType("spruce_button");
	public static final BlockType BIRCH_BUTTON = getBlockType("birch_button");
	public static final BlockType JUNGLE_BUTTON = getBlockType("jungle_button");
	public static final BlockType ACACIA_BUTTON = getBlockType("acacia_button");
	public static final BlockType DARK_OAK_BUTTON = getBlockType("dark_oak_button");
	public static final BlockType SKELETON_SKULL = getBlockType("skeleton_skull");
	public static final BlockType SKELETON_WALL_SKULL = getBlockType("skeleton_wall_skull");
	public static final BlockType WITHER_SKELETON_SKULL = getBlockType("wither_skeleton_skull");
	public static final BlockType WITHER_SKELETON_WALL_SKULL = getBlockType("wither_skeleton_wall_skull");
	public static final BlockType ZOMBIE_HEAD = getBlockType("zombie_head");
	public static final BlockType ZOMBIE_WALL_HEAD = getBlockType("zombie_wall_head");
	public static final BlockType PLAYER_HEAD = getBlockType("player_head");
	public static final BlockType PLAYER_WALL_HEAD = getBlockType("player_wall_head");
	public static final BlockType CREEPER_HEAD = getBlockType("creeper_head");
	public static final BlockType CREEPER_WALL_HEAD = getBlockType("creeper_wall_head");
	public static final BlockType DRAGON_HEAD = getBlockType("dragon_head");
	public static final BlockType DRAGON_WALL_HEAD = getBlockType("dragon_wall_head");
	public static final BlockType ANVIL = getBlockType("anvil");
	public static final BlockType CHIPPED_ANVIL = getBlockType("chipped_anvil");
	public static final BlockType DAMAGED_ANVIL = getBlockType("damaged_anvil");
	public static final BlockType TRAPPED_CHEST = getBlockType("trapped_chest");
	public static final BlockType LIGHT_WEIGHTED_PRESSURE_PLATE = getBlockType("light_weighted_pressure_plate");
	public static final BlockType HEAVY_WEIGHTED_PRESSURE_PLATE = getBlockType("heavy_weighted_pressure_plate");
	public static final BlockType COMPARATOR = getBlockType("comparator");
	public static final BlockType DAYLIGHT_DETECTOR = getBlockType("daylight_detector");
	public static final BlockType REDSTONE_BLOCK = getBlockType("redstone_block");
	public static final BlockType NETHER_QUARTZ_ORE = getBlockType("nether_quartz_ore");
	public static final BlockType HOPPER = getBlockType("hopper");
	public static final BlockType QUARTZ_BLOCK = getBlockType("quartz_block");
	public static final BlockType CHISELED_QUARTZ_BLOCK = getBlockType("chiseled_quartz_block");
	public static final BlockType QUARTZ_PILLAR = getBlockType("quartz_pillar");
	public static final BlockType QUARTZ_STAIRS = getBlockType("quartz_stairs");
	public static final BlockType ACTIVATOR_RAIL = getBlockType("activator_rail");
	public static final BlockType DROPPER = getBlockType("dropper");
	public static final BlockType WHITE_TERRACOTTA = getBlockType("white_terracotta");
	public static final BlockType ORANGE_TERRACOTTA = getBlockType("orange_terracotta");
	public static final BlockType MAGENTA_TERRACOTTA = getBlockType("magenta_terracotta");
	public static final BlockType LIGHT_BLUE_TERRACOTTA = getBlockType("light_blue_terracotta");
	public static final BlockType YELLOW_TERRACOTTA = getBlockType("yellow_terracotta");
	public static final BlockType LIME_TERRACOTTA = getBlockType("lime_terracotta");
	public static final BlockType PINK_TERRACOTTA = getBlockType("pink_terracotta");
	public static final BlockType GRAY_TERRACOTTA = getBlockType("gray_terracotta");
	public static final BlockType LIGHT_GRAY_TERRACOTTA = getBlockType("light_gray_terracotta");
	public static final BlockType CYAN_TERRACOTTA = getBlockType("cyan_terracotta");
	public static final BlockType PURPLE_TERRACOTTA = getBlockType("purple_terracotta");
	public static final BlockType BLUE_TERRACOTTA = getBlockType("blue_terracotta");
	public static final BlockType BROWN_TERRACOTTA = getBlockType("brown_terracotta");
	public static final BlockType GREEN_TERRACOTTA = getBlockType("green_terracotta");
	public static final BlockType RED_TERRACOTTA = getBlockType("red_terracotta");
	public static final BlockType BLACK_TERRACOTTA = getBlockType("black_terracotta");
	public static final BlockType WHITE_STAINED_GLASS_PANE = getBlockType("white_stained_glass_pane");
	public static final BlockType ORANGE_STAINED_GLASS_PANE = getBlockType("orange_stained_glass_pane");
	public static final BlockType MAGENTA_STAINED_GLASS_PANE = getBlockType("magenta_stained_glass_pane");
	public static final BlockType LIGHT_BLUE_STAINED_GLASS_PANE = getBlockType("light_blue_stained_glass_pane");
	public static final BlockType YELLOW_STAINED_GLASS_PANE = getBlockType("yellow_stained_glass_pane");
	public static final BlockType LIME_STAINED_GLASS_PANE = getBlockType("lime_stained_glass_pane");
	public static final BlockType PINK_STAINED_GLASS_PANE = getBlockType("pink_stained_glass_pane");
	public static final BlockType GRAY_STAINED_GLASS_PANE = getBlockType("gray_stained_glass_pane");
	public static final BlockType LIGHT_GRAY_STAINED_GLASS_PANE = getBlockType("light_gray_stained_glass_pane");
	public static final BlockType CYAN_STAINED_GLASS_PANE = getBlockType("cyan_stained_glass_pane");
	public static final BlockType PURPLE_STAINED_GLASS_PANE = getBlockType("purple_stained_glass_pane");
	public static final BlockType BLUE_STAINED_GLASS_PANE = getBlockType("blue_stained_glass_pane");
	public static final BlockType BROWN_STAINED_GLASS_PANE = getBlockType("brown_stained_glass_pane");
	public static final BlockType GREEN_STAINED_GLASS_PANE = getBlockType("green_stained_glass_pane");
	public static final BlockType RED_STAINED_GLASS_PANE = getBlockType("red_stained_glass_pane");
	public static final BlockType BLACK_STAINED_GLASS_PANE = getBlockType("black_stained_glass_pane");
	public static final BlockType ACACIA_STAIRS = getBlockType("acacia_stairs");
	public static final BlockType DARK_OAK_STAIRS = getBlockType("dark_oak_stairs");
	public static final BlockType SLIME_BLOCK = getBlockType("slime_block");
	public static final BlockType BARRIER = getBlockType("barrier");
	public static final BlockType IRON_TRAPDOOR = getBlockType("iron_trapdoor");
	public static final BlockType PRISMARINE = getBlockType("prismarine");
	public static final BlockType PRISMARINE_BRICKS = getBlockType("prismarine_bricks");
	public static final BlockType DARK_PRISMARINE = getBlockType("dark_prismarine");
	public static final BlockType PRISMARINE_STAIRS = getBlockType("prismarine_stairs");
	public static final BlockType PRISMARINE_BRICK_STAIRS = getBlockType("prismarine_brick_stairs");
	public static final BlockType DARK_PRISMARINE_STAIRS = getBlockType("dark_prismarine_stairs");
	public static final BlockType PRISMARINE_SLAB = getBlockType("prismarine_slab");
	public static final BlockType PRISMARINE_BRICK_SLAB = getBlockType("prismarine_brick_slab");
	public static final BlockType DARK_PRISMARINE_SLAB = getBlockType("dark_prismarine_slab");
	public static final BlockType SEA_LANTERN = getBlockType("sea_lantern");
	public static final BlockType HAY_BLOCK = getBlockType("hay_block");
	public static final BlockType WHITE_CARPET = getBlockType("white_carpet");
	public static final BlockType ORANGE_CARPET = getBlockType("orange_carpet");
	public static final BlockType MAGENTA_CARPET = getBlockType("magenta_carpet");
	public static final BlockType LIGHT_BLUE_CARPET = getBlockType("light_blue_carpet");
	public static final BlockType YELLOW_CARPET = getBlockType("yellow_carpet");
	public static final BlockType LIME_CARPET = getBlockType("lime_carpet");
	public static final BlockType PINK_CARPET = getBlockType("pink_carpet");
	public static final BlockType GRAY_CARPET = getBlockType("gray_carpet");
	public static final BlockType LIGHT_GRAY_CARPET = getBlockType("light_gray_carpet");
	public static final BlockType CYAN_CARPET = getBlockType("cyan_carpet");
	public static final BlockType PURPLE_CARPET = getBlockType("purple_carpet");
	public static final BlockType BLUE_CARPET = getBlockType("blue_carpet");
	public static final BlockType BROWN_CARPET = getBlockType("brown_carpet");
	public static final BlockType GREEN_CARPET = getBlockType("green_carpet");
	public static final BlockType RED_CARPET = getBlockType("red_carpet");
	public static final BlockType BLACK_CARPET = getBlockType("black_carpet");
	public static final BlockType TERRACOTTA = getBlockType("terracotta");
	public static final BlockType COAL_BLOCK = getBlockType("coal_block");
	public static final BlockType PACKED_ICE = getBlockType("packed_ice");
	public static final BlockType SUNFLOWER = getBlockType("sunflower");
	public static final BlockType LILAC = getBlockType("lilac");
	public static final BlockType ROSE_BUSH = getBlockType("rose_bush");
	public static final BlockType PEONY = getBlockType("peony");
	public static final BlockType TALL_GRASS = getBlockType("tall_grass");
	public static final BlockType LARGE_FERN = getBlockType("large_fern");
	public static final BlockType WHITE_BANNER = getBlockType("white_banner");
	public static final BlockType ORANGE_BANNER = getBlockType("orange_banner");
	public static final BlockType MAGENTA_BANNER = getBlockType("magenta_banner");
	public static final BlockType LIGHT_BLUE_BANNER = getBlockType("light_blue_banner");
	public static final BlockType YELLOW_BANNER = getBlockType("yellow_banner");
	public static final BlockType LIME_BANNER = getBlockType("lime_banner");
	public static final BlockType PINK_BANNER = getBlockType("pink_banner");
	public static final BlockType GRAY_BANNER = getBlockType("gray_banner");
	public static final BlockType LIGHT_GRAY_BANNER = getBlockType("light_gray_banner");
	public static final BlockType CYAN_BANNER = getBlockType("cyan_banner");
	public static final BlockType PURPLE_BANNER = getBlockType("purple_banner");
	public static final BlockType BLUE_BANNER = getBlockType("blue_banner");
	public static final BlockType BROWN_BANNER = getBlockType("brown_banner");
	public static final BlockType GREEN_BANNER = getBlockType("green_banner");
	public static final BlockType RED_BANNER = getBlockType("red_banner");
	public static final BlockType BLACK_BANNER = getBlockType("black_banner");
	public static final BlockType WHITE_WALL_BANNER = getBlockType("white_wall_banner");
	public static final BlockType ORANGE_WALL_BANNER = getBlockType("orange_wall_banner");
	public static final BlockType MAGENTA_WALL_BANNER = getBlockType("magenta_wall_banner");
	public static final BlockType LIGHT_BLUE_WALL_BANNER = getBlockType("light_blue_wall_banner");
	public static final BlockType YELLOW_WALL_BANNER = getBlockType("yellow_wall_banner");
	public static final BlockType LIME_WALL_BANNER = getBlockType("lime_wall_banner");
	public static final BlockType PINK_WALL_BANNER = getBlockType("pink_wall_banner");
	public static final BlockType GRAY_WALL_BANNER = getBlockType("gray_wall_banner");
	public static final BlockType LIGHT_GRAY_WALL_BANNER = getBlockType("light_gray_wall_banner");
	public static final BlockType CYAN_WALL_BANNER = getBlockType("cyan_wall_banner");
	public static final BlockType PURPLE_WALL_BANNER = getBlockType("purple_wall_banner");
	public static final BlockType BLUE_WALL_BANNER = getBlockType("blue_wall_banner");
	public static final BlockType BROWN_WALL_BANNER = getBlockType("brown_wall_banner");
	public static final BlockType GREEN_WALL_BANNER = getBlockType("green_wall_banner");
	public static final BlockType RED_WALL_BANNER = getBlockType("red_wall_banner");
	public static final BlockType BLACK_WALL_BANNER = getBlockType("black_wall_banner");
	public static final BlockType RED_SANDSTONE = getBlockType("red_sandstone");
	public static final BlockType CHISELED_RED_SANDSTONE = getBlockType("chiseled_red_sandstone");
	public static final BlockType CUT_RED_SANDSTONE = getBlockType("cut_red_sandstone");
	public static final BlockType RED_SANDSTONE_STAIRS = getBlockType("red_sandstone_stairs");
	public static final BlockType OAK_SLAB = getBlockType("oak_slab");
	public static final BlockType SPRUCE_SLAB = getBlockType("spruce_slab");
	public static final BlockType BIRCH_SLAB = getBlockType("birch_slab");
	public static final BlockType JUNGLE_SLAB = getBlockType("jungle_slab");
	public static final BlockType ACACIA_SLAB = getBlockType("acacia_slab");
	public static final BlockType DARK_OAK_SLAB = getBlockType("dark_oak_slab");
	public static final BlockType STONE_SLAB = getBlockType("stone_slab");
	public static final BlockType SMOOTH_STONE_SLAB = getBlockType("smooth_stone_slab");
	public static final BlockType SANDSTONE_SLAB = getBlockType("sandstone_slab");
	public static final BlockType CUT_SANDSTONE_SLAB = getBlockType("cut_sandstone_slab");
	public static final BlockType PETRIFIED_OAK_SLAB = getBlockType("petrified_oak_slab");
	public static final BlockType COBBLESTONE_SLAB = getBlockType("cobblestone_slab");
	public static final BlockType BRICK_SLAB = getBlockType("brick_slab");
	public static final BlockType STONE_BRICK_SLAB = getBlockType("stone_brick_slab");
	public static final BlockType NETHER_BRICK_SLAB = getBlockType("nether_brick_slab");
	public static final BlockType QUARTZ_SLAB = getBlockType("quartz_slab");
	public static final BlockType RED_SANDSTONE_SLAB = getBlockType("red_sandstone_slab");
	public static final BlockType CUT_RED_SANDSTONE_SLAB = getBlockType("cut_red_sandstone_slab");
	public static final BlockType PURPUR_SLAB = getBlockType("purpur_slab");
	public static final BlockType SMOOTH_STONE = getBlockType("smooth_stone");
	public static final BlockType SMOOTH_SANDSTONE = getBlockType("smooth_sandstone");
	public static final BlockType SMOOTH_QUARTZ = getBlockType("smooth_quartz");
	public static final BlockType SMOOTH_RED_SANDSTONE = getBlockType("smooth_red_sandstone");
	public static final BlockType SPRUCE_FENCE_GATE = getBlockType("spruce_fence_gate");
	public static final BlockType BIRCH_FENCE_GATE = getBlockType("birch_fence_gate");
	public static final BlockType JUNGLE_FENCE_GATE = getBlockType("jungle_fence_gate");
	public static final BlockType ACACIA_FENCE_GATE = getBlockType("acacia_fence_gate");
	public static final BlockType DARK_OAK_FENCE_GATE = getBlockType("dark_oak_fence_gate");
	public static final BlockType SPRUCE_FENCE = getBlockType("spruce_fence");
	public static final BlockType BIRCH_FENCE = getBlockType("birch_fence");
	public static final BlockType JUNGLE_FENCE = getBlockType("jungle_fence");
	public static final BlockType ACACIA_FENCE = getBlockType("acacia_fence");
	public static final BlockType DARK_OAK_FENCE = getBlockType("dark_oak_fence");
	public static final BlockType SPRUCE_DOOR = getBlockType("spruce_door");
	public static final BlockType BIRCH_DOOR = getBlockType("birch_door");
	public static final BlockType JUNGLE_DOOR = getBlockType("jungle_door");
	public static final BlockType ACACIA_DOOR = getBlockType("acacia_door");
	public static final BlockType DARK_OAK_DOOR = getBlockType("dark_oak_door");
	public static final BlockType END_ROD = getBlockType("end_rod");
	public static final BlockType CHORUS_PLANT = getBlockType("chorus_plant");
	public static final BlockType CHORUS_FLOWER = getBlockType("chorus_flower");
	public static final BlockType PURPUR_BLOCK = getBlockType("purpur_block");
	public static final BlockType PURPUR_PILLAR = getBlockType("purpur_pillar");
	public static final BlockType PURPUR_STAIRS = getBlockType("purpur_stairs");
	public static final BlockType END_STONE_BRICKS = getBlockType("end_stone_bricks");
	public static final BlockType BEETROOTS = getBlockType("beetroots");
	public static final BlockType GRASS_PATH = getBlockType("grass_path");
	public static final BlockType END_GATEWAY = getBlockType("end_gateway");
	public static final BlockType REPEATING_COMMAND_BLOCK = getBlockType("repeating_command_block");
	public static final BlockType CHAIN_COMMAND_BLOCK = getBlockType("chain_command_block");
	public static final BlockType FROSTED_ICE = getBlockType("frosted_ice");
	public static final BlockType MAGMA_BLOCK = getBlockType("magma_block");
	public static final BlockType NETHER_WART_BLOCK = getBlockType("nether_wart_block");
	public static final BlockType RED_NETHER_BRICKS = getBlockType("red_nether_bricks");
	public static final BlockType BONE_BLOCK = getBlockType("bone_block");
	public static final BlockType STRUCTURE_VOID = getBlockType("structure_void");
	public static final BlockType OBSERVER = getBlockType("observer");
	public static final BlockType SHULKER_BOX = getBlockType("shulker_box");
	public static final BlockType WHITE_SHULKER_BOX = getBlockType("white_shulker_box");
	public static final BlockType ORANGE_SHULKER_BOX = getBlockType("orange_shulker_box");
	public static final BlockType MAGENTA_SHULKER_BOX = getBlockType("magenta_shulker_box");
	public static final BlockType LIGHT_BLUE_SHULKER_BOX = getBlockType("light_blue_shulker_box");
	public static final BlockType YELLOW_SHULKER_BOX = getBlockType("yellow_shulker_box");
	public static final BlockType LIME_SHULKER_BOX = getBlockType("lime_shulker_box");
	public static final BlockType PINK_SHULKER_BOX = getBlockType("pink_shulker_box");
	public static final BlockType GRAY_SHULKER_BOX = getBlockType("gray_shulker_box");
	public static final BlockType LIGHT_GRAY_SHULKER_BOX = getBlockType("light_gray_shulker_box");
	public static final BlockType CYAN_SHULKER_BOX = getBlockType("cyan_shulker_box");
	public static final BlockType PURPLE_SHULKER_BOX = getBlockType("purple_shulker_box");
	public static final BlockType BLUE_SHULKER_BOX = getBlockType("blue_shulker_box");
	public static final BlockType BROWN_SHULKER_BOX = getBlockType("brown_shulker_box");
	public static final BlockType GREEN_SHULKER_BOX = getBlockType("green_shulker_box");
	public static final BlockType RED_SHULKER_BOX = getBlockType("red_shulker_box");
	public static final BlockType BLACK_SHULKER_BOX = getBlockType("black_shulker_box");
	public static final BlockType WHITE_GLAZED_TERRACOTTA = getBlockType("white_glazed_terracotta");
	public static final BlockType ORANGE_GLAZED_TERRACOTTA = getBlockType("orange_glazed_terracotta");
	public static final BlockType MAGENTA_GLAZED_TERRACOTTA = getBlockType("magenta_glazed_terracotta");
	public static final BlockType LIGHT_BLUE_GLAZED_TERRACOTTA = getBlockType("light_blue_glazed_terracotta");
	public static final BlockType YELLOW_GLAZED_TERRACOTTA = getBlockType("yellow_glazed_terracotta");
	public static final BlockType LIME_GLAZED_TERRACOTTA = getBlockType("lime_glazed_terracotta");
	public static final BlockType PINK_GLAZED_TERRACOTTA = getBlockType("pink_glazed_terracotta");
	public static final BlockType GRAY_GLAZED_TERRACOTTA = getBlockType("gray_glazed_terracotta");
	public static final BlockType LIGHT_GRAY_GLAZED_TERRACOTTA = getBlockType("light_gray_glazed_terracotta");
	public static final BlockType CYAN_GLAZED_TERRACOTTA = getBlockType("cyan_glazed_terracotta");
	public static final BlockType PURPLE_GLAZED_TERRACOTTA = getBlockType("purple_glazed_terracotta");
	public static final BlockType BLUE_GLAZED_TERRACOTTA = getBlockType("blue_glazed_terracotta");
	public static final BlockType BROWN_GLAZED_TERRACOTTA = getBlockType("brown_glazed_terracotta");
	public static final BlockType GREEN_GLAZED_TERRACOTTA = getBlockType("green_glazed_terracotta");
	public static final BlockType RED_GLAZED_TERRACOTTA = getBlockType("red_glazed_terracotta");
	public static final BlockType BLACK_GLAZED_TERRACOTTA = getBlockType("black_glazed_terracotta");
	public static final BlockType WHITE_CONCRETE = getBlockType("white_concrete");
	public static final BlockType ORANGE_CONCRETE = getBlockType("orange_concrete");
	public static final BlockType MAGENTA_CONCRETE = getBlockType("magenta_concrete");
	public static final BlockType LIGHT_BLUE_CONCRETE = getBlockType("light_blue_concrete");
	public static final BlockType YELLOW_CONCRETE = getBlockType("yellow_concrete");
	public static final BlockType LIME_CONCRETE = getBlockType("lime_concrete");
	public static final BlockType PINK_CONCRETE = getBlockType("pink_concrete");
	public static final BlockType GRAY_CONCRETE = getBlockType("gray_concrete");
	public static final BlockType LIGHT_GRAY_CONCRETE = getBlockType("light_gray_concrete");
	public static final BlockType CYAN_CONCRETE = getBlockType("cyan_concrete");
	public static final BlockType PURPLE_CONCRETE = getBlockType("purple_concrete");
	public static final BlockType BLUE_CONCRETE = getBlockType("blue_concrete");
	public static final BlockType BROWN_CONCRETE = getBlockType("brown_concrete");
	public static final BlockType GREEN_CONCRETE = getBlockType("green_concrete");
	public static final BlockType RED_CONCRETE = getBlockType("red_concrete");
	public static final BlockType BLACK_CONCRETE = getBlockType("black_concrete");
	public static final BlockType WHITE_CONCRETE_POWDER = getBlockType("white_concrete_powder");
	public static final BlockType ORANGE_CONCRETE_POWDER = getBlockType("orange_concrete_powder");
	public static final BlockType MAGENTA_CONCRETE_POWDER = getBlockType("magenta_concrete_powder");
	public static final BlockType LIGHT_BLUE_CONCRETE_POWDER = getBlockType("light_blue_concrete_powder");
	public static final BlockType YELLOW_CONCRETE_POWDER = getBlockType("yellow_concrete_powder");
	public static final BlockType LIME_CONCRETE_POWDER = getBlockType("lime_concrete_powder");
	public static final BlockType PINK_CONCRETE_POWDER = getBlockType("pink_concrete_powder");
	public static final BlockType GRAY_CONCRETE_POWDER = getBlockType("gray_concrete_powder");
	public static final BlockType LIGHT_GRAY_CONCRETE_POWDER = getBlockType("light_gray_concrete_powder");
	public static final BlockType CYAN_CONCRETE_POWDER = getBlockType("cyan_concrete_powder");
	public static final BlockType PURPLE_CONCRETE_POWDER = getBlockType("purple_concrete_powder");
	public static final BlockType BLUE_CONCRETE_POWDER = getBlockType("blue_concrete_powder");
	public static final BlockType BROWN_CONCRETE_POWDER = getBlockType("brown_concrete_powder");
	public static final BlockType GREEN_CONCRETE_POWDER = getBlockType("green_concrete_powder");
	public static final BlockType RED_CONCRETE_POWDER = getBlockType("red_concrete_powder");
	public static final BlockType BLACK_CONCRETE_POWDER = getBlockType("black_concrete_powder");
	public static final BlockType KELP = getBlockType("kelp");
	public static final BlockType KELP_PLANT = getBlockType("kelp_plant");
	public static final BlockType DRIED_KELP_BLOCK = getBlockType("dried_kelp_block");
	public static final BlockType TURTLE_EGG = getBlockType("turtle_egg");
	public static final BlockType DEAD_TUBE_CORAL_BLOCK = getBlockType("dead_tube_coral_block");
	public static final BlockType DEAD_BRAIN_CORAL_BLOCK = getBlockType("dead_brain_coral_block");
	public static final BlockType DEAD_BUBBLE_CORAL_BLOCK = getBlockType("dead_bubble_coral_block");
	public static final BlockType DEAD_FIRE_CORAL_BLOCK = getBlockType("dead_fire_coral_block");
	public static final BlockType DEAD_HORN_CORAL_BLOCK = getBlockType("dead_horn_coral_block");
	public static final BlockType TUBE_CORAL_BLOCK = getBlockType("tube_coral_block");
	public static final BlockType BRAIN_CORAL_BLOCK = getBlockType("brain_coral_block");
	public static final BlockType BUBBLE_CORAL_BLOCK = getBlockType("bubble_coral_block");
	public static final BlockType FIRE_CORAL_BLOCK = getBlockType("fire_coral_block");
	public static final BlockType HORN_CORAL_BLOCK = getBlockType("horn_coral_block");
	public static final BlockType DEAD_TUBE_CORAL = getBlockType("dead_tube_coral");
	public static final BlockType DEAD_BRAIN_CORAL = getBlockType("dead_brain_coral");
	public static final BlockType DEAD_BUBBLE_CORAL = getBlockType("dead_bubble_coral");
	public static final BlockType DEAD_FIRE_CORAL = getBlockType("dead_fire_coral");
	public static final BlockType DEAD_HORN_CORAL = getBlockType("dead_horn_coral");
	public static final BlockType TUBE_CORAL = getBlockType("tube_coral");
	public static final BlockType BRAIN_CORAL = getBlockType("brain_coral");
	public static final BlockType BUBBLE_CORAL = getBlockType("bubble_coral");
	public static final BlockType FIRE_CORAL = getBlockType("fire_coral");
	public static final BlockType HORN_CORAL = getBlockType("horn_coral");
	public static final BlockType DEAD_TUBE_CORAL_FAN = getBlockType("dead_tube_coral_fan");
	public static final BlockType DEAD_BRAIN_CORAL_FAN = getBlockType("dead_brain_coral_fan");
	public static final BlockType DEAD_BUBBLE_CORAL_FAN = getBlockType("dead_bubble_coral_fan");
	public static final BlockType DEAD_FIRE_CORAL_FAN = getBlockType("dead_fire_coral_fan");
	public static final BlockType DEAD_HORN_CORAL_FAN = getBlockType("dead_horn_coral_fan");
	public static final BlockType TUBE_CORAL_FAN = getBlockType("tube_coral_fan");
	public static final BlockType BRAIN_CORAL_FAN = getBlockType("brain_coral_fan");
	public static final BlockType BUBBLE_CORAL_FAN = getBlockType("bubble_coral_fan");
	public static final BlockType FIRE_CORAL_FAN = getBlockType("fire_coral_fan");
	public static final BlockType HORN_CORAL_FAN = getBlockType("horn_coral_fan");
	public static final BlockType DEAD_TUBE_CORAL_WALL_FAN = getBlockType("dead_tube_coral_wall_fan");
	public static final BlockType DEAD_BRAIN_CORAL_WALL_FAN = getBlockType("dead_brain_coral_wall_fan");
	public static final BlockType DEAD_BUBBLE_CORAL_WALL_FAN = getBlockType("dead_bubble_coral_wall_fan");
	public static final BlockType DEAD_FIRE_CORAL_WALL_FAN = getBlockType("dead_fire_coral_wall_fan");
	public static final BlockType DEAD_HORN_CORAL_WALL_FAN = getBlockType("dead_horn_coral_wall_fan");
	public static final BlockType TUBE_CORAL_WALL_FAN = getBlockType("tube_coral_wall_fan");
	public static final BlockType BRAIN_CORAL_WALL_FAN = getBlockType("brain_coral_wall_fan");
	public static final BlockType BUBBLE_CORAL_WALL_FAN = getBlockType("bubble_coral_wall_fan");
	public static final BlockType FIRE_CORAL_WALL_FAN = getBlockType("fire_coral_wall_fan");
	public static final BlockType HORN_CORAL_WALL_FAN = getBlockType("horn_coral_wall_fan");
	public static final BlockType SEA_PICKLE = getBlockType("sea_pickle");
	public static final BlockType BLUE_ICE = getBlockType("blue_ice");
	public static final BlockType CONDUIT = getBlockType("conduit");
	public static final BlockType BAMBOO_SAPLING = getBlockType("bamboo_sapling");
	public static final BlockType BAMBOO = getBlockType("bamboo");
	public static final BlockType POTTED_BAMBOO = getBlockType("potted_bamboo");
	public static final BlockType VOID_AIR = getBlockType("void_air");
	public static final BlockType CAVE_AIR = getBlockType("cave_air");
	public static final BlockType BUBBLE_COLUMN = getBlockType("bubble_column");
	public static final BlockType POLISHED_GRANITE_STAIRS = getBlockType("polished_granite_stairs");
	public static final BlockType SMOOTH_RED_SANDSTONE_STAIRS = getBlockType("smooth_red_sandstone_stairs");
	public static final BlockType MOSSY_STONE_BRICK_STAIRS = getBlockType("mossy_stone_brick_stairs");
	public static final BlockType POLISHED_DIORITE_STAIRS = getBlockType("polished_diorite_stairs");
	public static final BlockType MOSSY_COBBLESTONE_STAIRS = getBlockType("mossy_cobblestone_stairs");
	public static final BlockType END_STONE_BRICK_STAIRS = getBlockType("end_stone_brick_stairs");
	public static final BlockType STONE_STAIRS = getBlockType("stone_stairs");
	public static final BlockType SMOOTH_SANDSTONE_STAIRS = getBlockType("smooth_sandstone_stairs");
	public static final BlockType SMOOTH_QUARTZ_STAIRS = getBlockType("smooth_quartz_stairs");
	public static final BlockType GRANITE_STAIRS = getBlockType("granite_stairs");
	public static final BlockType ANDESITE_STAIRS = getBlockType("andesite_stairs");
	public static final BlockType RED_NETHER_BRICK_STAIRS = getBlockType("red_nether_brick_stairs");
	public static final BlockType POLISHED_ANDESITE_STAIRS = getBlockType("polished_andesite_stairs");
	public static final BlockType DIORITE_STAIRS = getBlockType("diorite_stairs");
	public static final BlockType POLISHED_GRANITE_SLAB = getBlockType("polished_granite_slab");
	public static final BlockType SMOOTH_RED_SANDSTONE_SLAB = getBlockType("smooth_red_sandstone_slab");
	public static final BlockType MOSSY_STONE_BRICK_SLAB = getBlockType("mossy_stone_brick_slab");
	public static final BlockType POLISHED_DIORITE_SLAB = getBlockType("polished_diorite_slab");
	public static final BlockType MOSSY_COBBLESTONE_SLAB = getBlockType("mossy_cobblestone_slab");
	public static final BlockType END_STONE_BRICK_SLAB = getBlockType("end_stone_brick_slab");
	public static final BlockType SMOOTH_SANDSTONE_SLAB = getBlockType("smooth_sandstone_slab");
	public static final BlockType SMOOTH_QUARTZ_SLAB = getBlockType("smooth_quartz_slab");
	public static final BlockType GRANITE_SLAB = getBlockType("granite_slab");
	public static final BlockType ANDESITE_SLAB = getBlockType("andesite_slab");
	public static final BlockType RED_NETHER_BRICK_SLAB = getBlockType("red_nether_brick_slab");
	public static final BlockType POLISHED_ANDESITE_SLAB = getBlockType("polished_andesite_slab");
	public static final BlockType DIORITE_SLAB = getBlockType("diorite_slab");
	public static final BlockType BRICK_WALL = getBlockType("brick_wall");
	public static final BlockType PRISMARINE_WALL = getBlockType("prismarine_wall");
	public static final BlockType RED_SANDSTONE_WALL = getBlockType("red_sandstone_wall");
	public static final BlockType MOSSY_STONE_BRICK_WALL = getBlockType("mossy_stone_brick_wall");
	public static final BlockType GRANITE_WALL = getBlockType("granite_wall");
	public static final BlockType STONE_BRICK_WALL = getBlockType("stone_brick_wall");
	public static final BlockType NETHER_BRICK_WALL = getBlockType("nether_brick_wall");
	public static final BlockType ANDESITE_WALL = getBlockType("andesite_wall");
	public static final BlockType RED_NETHER_BRICK_WALL = getBlockType("red_nether_brick_wall");
	public static final BlockType SANDSTONE_WALL = getBlockType("sandstone_wall");
	public static final BlockType END_STONE_BRICK_WALL = getBlockType("end_stone_brick_wall");
	public static final BlockType DIORITE_WALL = getBlockType("diorite_wall");
	public static final BlockType SCAFFOLDING = getBlockType("scaffolding");
	public static final BlockType LOOM = getBlockType("loom");
	public static final BlockType BARREL = getBlockType("barrel");
	public static final BlockType SMOKER = getBlockType("smoker");
	public static final BlockType BLAST_FURNACE = getBlockType("blast_furnace");
	public static final BlockType CARTOGRAPHY_TABLE = getBlockType("cartography_table");
	public static final BlockType FLETCHING_TABLE = getBlockType("fletching_table");
	public static final BlockType GRINDSTONE = getBlockType("grindstone");
	public static final BlockType LECTERN = getBlockType("lectern");
	public static final BlockType SMITHING_TABLE = getBlockType("smithing_table");
	public static final BlockType STONECUTTER = getBlockType("stonecutter");
	public static final BlockType BELL = getBlockType("bell");
	public static final BlockType LANTERN = getBlockType("lantern");
	public static final BlockType SOUL_LANTERN = getBlockType("soul_lantern");
	public static final BlockType CAMPFIRE = getBlockType("campfire");
	public static final BlockType SOUL_CAMPFIRE = getBlockType("soul_campfire");
	public static final BlockType SWEET_BERRY_BUSH = getBlockType("sweet_berry_bush");
	public static final BlockType WARPED_STEM = getBlockType("warped_stem");
	public static final BlockType STRIPPED_WARPED_STEM = getBlockType("stripped_warped_stem");
	public static final BlockType WARPED_HYPHAE = getBlockType("warped_hyphae");
	public static final BlockType STRIPPED_WARPED_HYPHAE = getBlockType("stripped_warped_hyphae");
	public static final BlockType WARPED_NYLIUM = getBlockType("warped_nylium");
	public static final BlockType WARPED_FUNGUS = getBlockType("warped_fungus");
	public static final BlockType WARPED_WART_BLOCK = getBlockType("warped_wart_block");
	public static final BlockType WARPED_ROOTS = getBlockType("warped_roots");
	public static final BlockType NETHER_SPROUTS = getBlockType("nether_sprouts");
	public static final BlockType CRIMSON_STEM = getBlockType("crimson_stem");
	public static final BlockType STRIPPED_CRIMSON_STEM = getBlockType("stripped_crimson_stem");
	public static final BlockType CRIMSON_HYPHAE = getBlockType("crimson_hyphae");
	public static final BlockType STRIPPED_CRIMSON_HYPHAE = getBlockType("stripped_crimson_hyphae");
	public static final BlockType CRIMSON_NYLIUM = getBlockType("crimson_nylium");
	public static final BlockType CRIMSON_FUNGUS = getBlockType("crimson_fungus");
	public static final BlockType SHROOMLIGHT = getBlockType("shroomlight");
	public static final BlockType WEEPING_VINES = getBlockType("weeping_vines");
	public static final BlockType WEEPING_VINES_PLANT = getBlockType("weeping_vines_plant");
	public static final BlockType TWISTING_VINES = getBlockType("twisting_vines");
	public static final BlockType TWISTING_VINES_PLANT = getBlockType("twisting_vines_plant");
	public static final BlockType CRIMSON_ROOTS = getBlockType("crimson_roots");
	public static final BlockType CRIMSON_PLANKS = getBlockType("crimson_planks");
	public static final BlockType WARPED_PLANKS = getBlockType("warped_planks");
	public static final BlockType CRIMSON_SLAB = getBlockType("crimson_slab");
	public static final BlockType WARPED_SLAB = getBlockType("warped_slab");
	public static final BlockType CRIMSON_PRESSURE_PLATE = getBlockType("crimson_pressure_plate");
	public static final BlockType WARPED_PRESSURE_PLATE = getBlockType("warped_pressure_plate");
	public static final BlockType CRIMSON_FENCE = getBlockType("crimson_fence");
	public static final BlockType WARPED_FENCE = getBlockType("warped_fence");
	public static final BlockType CRIMSON_TRAPDOOR = getBlockType("crimson_trapdoor");
	public static final BlockType WARPED_TRAPDOOR = getBlockType("warped_trapdoor");
	public static final BlockType CRIMSON_FENCE_GATE = getBlockType("crimson_fence_gate");
	public static final BlockType WARPED_FENCE_GATE = getBlockType("warped_fence_gate");
	public static final BlockType CRIMSON_STAIRS = getBlockType("crimson_stairs");
	public static final BlockType WARPED_STAIRS = getBlockType("warped_stairs");
	public static final BlockType CRIMSON_BUTTON = getBlockType("crimson_button");
	public static final BlockType WARPED_BUTTON = getBlockType("warped_button");
	public static final BlockType CRIMSON_DOOR = getBlockType("crimson_door");
	public static final BlockType WARPED_DOOR = getBlockType("warped_door");
	public static final BlockType CRIMSON_SIGN = getBlockType("crimson_sign");
	public static final BlockType WARPED_SIGN = getBlockType("warped_sign");
	public static final BlockType CRIMSON_WALL_SIGN = getBlockType("crimson_wall_sign");
	public static final BlockType WARPED_WALL_SIGN = getBlockType("warped_wall_sign");
	public static final BlockType STRUCTURE_BLOCK = getBlockType("structure_block");
	public static final BlockType JIGSAW = getBlockType("jigsaw");
	public static final BlockType COMPOSTER = getBlockType("composter");
	public static final BlockType TARGET = getBlockType("target");
	public static final BlockType BEE_NEST = getBlockType("bee_nest");
	public static final BlockType BEEHIVE = getBlockType("beehive");
	public static final BlockType HONEY_BLOCK = getBlockType("honey_block");
	public static final BlockType HONEYCOMB_BLOCK = getBlockType("honeycomb_block");
	public static final BlockType NETHERITE_BLOCK = getBlockType("netherite_block");
	public static final BlockType ANCIENT_DEBRIS = getBlockType("ancient_debris");
	public static final BlockType CRYING_OBSIDIAN = getBlockType("crying_obsidian");
	public static final BlockType RESPAWN_ANCHOR = getBlockType("respawn_anchor");
	public static final BlockType POTTED_CRIMSON_FUNGUS = getBlockType("potted_crimson_fungus");
	public static final BlockType POTTED_WARPED_FUNGUS = getBlockType("potted_warped_fungus");
	public static final BlockType POTTED_CRIMSON_ROOTS = getBlockType("potted_crimson_roots");
	public static final BlockType POTTED_WARPED_ROOTS = getBlockType("potted_warped_roots");
	public static final BlockType LODESTONE = getBlockType("lodestone");
	public static final BlockType BLACKSTONE = getBlockType("blackstone");
	public static final BlockType BLACKSTONE_STAIRS = getBlockType("blackstone_stairs");
	public static final BlockType BLACKSTONE_WALL = getBlockType("blackstone_wall");
	public static final BlockType BLACKSTONE_SLAB = getBlockType("blackstone_slab");
	public static final BlockType POLISHED_BLACKSTONE = getBlockType("polished_blackstone");
	public static final BlockType POLISHED_BLACKSTONE_BRICKS = getBlockType("polished_blackstone_bricks");
	public static final BlockType CRACKED_POLISHED_BLACKSTONE_BRICKS = getBlockType("cracked_polished_blackstone_bricks");
	public static final BlockType CHISELED_POLISHED_BLACKSTONE = getBlockType("chiseled_polished_blackstone");
	public static final BlockType POLISHED_BLACKSTONE_BRICK_SLAB = getBlockType("polished_blackstone_brick_slab");
	public static final BlockType POLISHED_BLACKSTONE_BRICK_STAIRS = getBlockType("polished_blackstone_brick_stairs");
	public static final BlockType POLISHED_BLACKSTONE_BRICK_WALL = getBlockType("polished_blackstone_brick_wall");
	public static final BlockType GILDED_BLACKSTONE = getBlockType("gilded_blackstone");
	public static final BlockType POLISHED_BLACKSTONE_STAIRS = getBlockType("polished_blackstone_stairs");
	public static final BlockType POLISHED_BLACKSTONE_SLAB = getBlockType("polished_blackstone_slab");
	public static final BlockType POLISHED_BLACKSTONE_PRESSURE_PLATE = getBlockType("polished_blackstone_pressure_plate");
	public static final BlockType POLISHED_BLACKSTONE_BUTTON = getBlockType("polished_blackstone_button");
	public static final BlockType POLISHED_BLACKSTONE_WALL = getBlockType("polished_blackstone_wall");
	public static final BlockType CHISELED_NETHER_BRICKS = getBlockType("chiseled_nether_bricks");
	public static final BlockType CRACKED_NETHER_BRICKS = getBlockType("cracked_nether_bricks");
	public static final BlockType QUARTZ_BRICKS = getBlockType("quartz_bricks");

}
